/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplicativo.keycontrol.gui;

import aplicativo.keycontrol.main.KeyControl;
import aplicativo.keycontrol.util.ThreadHoraUtil;
import aplicativo.keycontrol.util.MensagensUtil;

/**
 *
 * @author Edu
 */
public class MainFrame extends javax.swing.JFrame {

    Thread hora = null;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        if (KeyControl.getUsuarioLogado() != null) {
            LbNome.setText(KeyControl.getUsuarioLogado().getNome());
            LbTipo.setText(KeyControl.getUsuarioLogado().getTipoString());
            Painel.removeAll();
        } else {
            MensagensUtil.addMsg(KeyControl.mainFrame, "Usuário não logado.");
            KeyControl.mainFrame.dispose();
            KeyControl.loginFrame.setLocationRelativeTo(null);
            KeyControl.loginFrame.setVisible(true);
        }
        iniThreadHora();
    }

    private void iniThreadHora() {
        hora = new Thread(new ThreadHoraUtil());
        hora.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Infos = new javax.swing.JPanel();
        Usuario = new javax.swing.JPanel();
        LbNome = new javax.swing.JLabel();
        Tipo = new javax.swing.JPanel();
        LbTipo = new javax.swing.JLabel();
        Hora = new javax.swing.JPanel();
        LbHora = new javax.swing.JLabel();
        Menu = new javax.swing.JPanel();
        MenuUsuarios = new javax.swing.JButton();
        MenuChaves = new javax.swing.JButton();
        MenuEmprestimo = new javax.swing.JButton();
        MenuDevolucao = new javax.swing.JButton();
        MenuReserva = new javax.swing.JButton();
        Painel = new javax.swing.JPanel();
        AbasChaves = new javax.swing.JTabbedPane();
        CadastroChave = new javax.swing.JPanel();
        LabSalaCadC = new javax.swing.JLabel();
        LabCapCadC = new javax.swing.JLabel();
        LabTipoCadC = new javax.swing.JLabel();
        TxtSalaCadC = new javax.swing.JTextField();
        CBoxTipoCadC = new javax.swing.JComboBox();
        ButCadastroCadU1 = new javax.swing.JButton();
        TxtCapacidadeCadC = new javax.swing.JTextField();
        ListaChave = new javax.swing.JPanel();
        ScrollPaneTab2 = new javax.swing.JScrollPane();
        TblUser1 = new javax.swing.JTable();
        ButAtualizarL1 = new javax.swing.JButton();
        BuscaChave = new javax.swing.JPanel();
        LabIdB1 = new javax.swing.JLabel();
        LabLoginB1 = new javax.swing.JLabel();
        LabTipoB1 = new javax.swing.JLabel();
        TxtIdBusC = new javax.swing.JTextField();
        TxtSalaBusC = new javax.swing.JTextField();
        CBoxTipoBusC = new javax.swing.JComboBox();
        ButBuscarBusU1 = new javax.swing.JButton();
        LabLoginB2 = new javax.swing.JLabel();
        TxtCapacidadeBusC = new javax.swing.JTextField();
        LabLoginB4 = new javax.swing.JLabel();
        ScrollPaneTab4 = new javax.swing.JScrollPane();
        TblChave = new javax.swing.JTable();
        CBoxEstadoBusC = new javax.swing.JComboBox();
        AlteraChave = new javax.swing.JPanel();
        LabIdA1 = new javax.swing.JLabel();
        LabLoginA1 = new javax.swing.JLabel();
        LabSenhaNA1 = new javax.swing.JLabel();
        LabTipoA1 = new javax.swing.JLabel();
        TxtLoginAltC1 = new javax.swing.JTextField();
        TxtIdAltC1 = new javax.swing.JTextField();
        TxtSenhaNAltC1 = new javax.swing.JPasswordField();
        CBoxTipoAaltC1 = new javax.swing.JComboBox();
        ButExcluirAltC1 = new javax.swing.JButton();
        ButAlterarAltC1 = new javax.swing.JButton();
        AbasUsuarios = new javax.swing.JTabbedPane();
        CadastroUsuario = new javax.swing.JPanel();
        LabLoginC = new javax.swing.JLabel();
        LabSenhaC = new javax.swing.JLabel();
        LabSenhaRC = new javax.swing.JLabel();
        LabTipoC = new javax.swing.JLabel();
        LabNomeC = new javax.swing.JLabel();
        TxtNomeCadU = new javax.swing.JTextField();
        TxtUserCadU = new javax.swing.JTextField();
        TxtSenhaCadU = new javax.swing.JPasswordField();
        TxtSenhaRCadU = new javax.swing.JPasswordField();
        CBoxTipoCadU = new javax.swing.JComboBox();
        ButCadastroCadU = new javax.swing.JButton();
        ListaUsuario = new javax.swing.JPanel();
        ScrollPaneTab = new javax.swing.JScrollPane();
        TblUser = new javax.swing.JTable();
        ButAtualizarL = new javax.swing.JButton();
        BuscaUsuario = new javax.swing.JPanel();
        LabIdB = new javax.swing.JLabel();
        LabLoginB = new javax.swing.JLabel();
        LabTipoB = new javax.swing.JLabel();
        LabNomeB = new javax.swing.JLabel();
        TxtIdBusU = new javax.swing.JTextField();
        TxtLoginBusU = new javax.swing.JTextField();
        CBoxTipoBusU = new javax.swing.JComboBox();
        TxtNomeBusU = new javax.swing.JTextField();
        ScrollPaneTab1 = new javax.swing.JScrollPane();
        TblUserFiltro = new javax.swing.JTable();
        ButBuscarBusU = new javax.swing.JButton();
        AlteraUsuario = new javax.swing.JPanel();
        LabIdA = new javax.swing.JLabel();
        LabLoginA = new javax.swing.JLabel();
        LabSenhaNA = new javax.swing.JLabel();
        LabSenhaNRA = new javax.swing.JLabel();
        LabTipoA = new javax.swing.JLabel();
        LabNomeA = new javax.swing.JLabel();
        TxtLoginAltC = new javax.swing.JTextField();
        TxtIdAltC = new javax.swing.JTextField();
        TxtSenhaNAltC = new javax.swing.JPasswordField();
        TxtSenhaN2AltC = new javax.swing.JPasswordField();
        CBoxTipoAaltC = new javax.swing.JComboBox();
        TxtNomeAltC = new javax.swing.JTextField();
        ButExcluirAltC = new javax.swing.JButton();
        ButAlterarAltC = new javax.swing.JButton();
        AbaDevolucao = new javax.swing.JPanel();
        LabDevolucaoCod = new javax.swing.JLabel();
        TxtDevolucaoCod = new javax.swing.JTextField();
        LabDevolucaoSala = new javax.swing.JLabel();
        TxtDevolucaoSala = new javax.swing.JTextField();
        LabDevolucaoCap = new javax.swing.JLabel();
        TxtDevolucaoCap = new javax.swing.JTextField();
        LabDevolucaoID = new javax.swing.JLabel();
        TxtDevolucaoID = new javax.swing.JTextField();
        ButtonDevolucaoBuscar = new javax.swing.JButton();
        SeparatorDevolucao = new javax.swing.JSeparator();
        ButtonDevolucaoDevolver = new javax.swing.JButton();
        AbaEmprestimo = new javax.swing.JPanel();
        LabEmprestimoMatricula = new javax.swing.JLabel();
        TxtEmprestimoMatricula = new javax.swing.JTextField();
        LabEmprestimoNome = new javax.swing.JLabel();
        TxtEmprestimoNome = new javax.swing.JTextField();
        LabEmprestimoTipo = new javax.swing.JLabel();
        TxtEmprestimoTipo = new javax.swing.JTextField();
        ButtonEmprestimoPreencher = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        ButSair = new javax.swing.JButton();
        ButLogout = new javax.swing.JButton();
        ButLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Usuario.setBorder(javax.swing.BorderFactory.createTitledBorder("Usuário"));

        LbNome.setText("Nome");

        javax.swing.GroupLayout UsuarioLayout = new javax.swing.GroupLayout(Usuario);
        Usuario.setLayout(UsuarioLayout);
        UsuarioLayout.setHorizontalGroup(
            UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LbNome)
                .addContainerGap(93, Short.MAX_VALUE))
        );
        UsuarioLayout.setVerticalGroup(
            UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LbNome, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        Tipo.setBorder(javax.swing.BorderFactory.createTitledBorder("Perfil"));

        LbTipo.setText("Tipo");

        javax.swing.GroupLayout TipoLayout = new javax.swing.GroupLayout(Tipo);
        Tipo.setLayout(TipoLayout);
        TipoLayout.setHorizontalGroup(
            TipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TipoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LbTipo)
                .addContainerGap(100, Short.MAX_VALUE))
        );
        TipoLayout.setVerticalGroup(
            TipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LbTipo, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        Hora.setBorder(javax.swing.BorderFactory.createTitledBorder("Horário"));

        LbHora.setText("DD/MM/AA hh:mm:ss");

        javax.swing.GroupLayout HoraLayout = new javax.swing.GroupLayout(Hora);
        Hora.setLayout(HoraLayout);
        HoraLayout.setHorizontalGroup(
            HoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HoraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LbHora)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        HoraLayout.setVerticalGroup(
            HoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LbHora, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        javax.swing.GroupLayout InfosLayout = new javax.swing.GroupLayout(Infos);
        Infos.setLayout(InfosLayout);
        InfosLayout.setHorizontalGroup(
            InfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InfosLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Hora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        InfosLayout.setVerticalGroup(
            InfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InfosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(InfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Usuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Tipo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Hora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        Menu.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Menu"))));

        MenuUsuarios.setText("Usuários");
        MenuUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuUsuariosActionPerformed(evt);
            }
        });

        MenuChaves.setText("Chaves");
        MenuChaves.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuChavesActionPerformed(evt);
            }
        });

        MenuEmprestimo.setText("Empréstimo");
        MenuEmprestimo.setToolTipText("");
        MenuEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuEmprestimoActionPerformed(evt);
            }
        });

        MenuDevolucao.setText("Devolução");
        MenuDevolucao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuDevolucaoActionPerformed(evt);
            }
        });

        MenuReserva.setText("Reserva");
        MenuReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuReservaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addComponent(MenuUsuarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MenuChaves)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MenuEmprestimo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MenuDevolucao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MenuReserva)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(MenuUsuarios)
                .addComponent(MenuChaves)
                .addComponent(MenuEmprestimo)
                .addComponent(MenuDevolucao)
                .addComponent(MenuReserva))
        );

        Painel.setLayout(new java.awt.CardLayout());

        AbasChaves.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        AbasChaves.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        AbasChaves.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        AbasChaves.setPreferredSize(new java.awt.Dimension(500, 600));

        LabSalaCadC.setText("Sala");

        LabCapCadC.setText("Capacidade");

        LabTipoCadC.setText("Tipo");

        CBoxTipoCadC.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "S", "L", "R" }));
        CBoxTipoCadC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBoxTipoCadCActionPerformed(evt);
            }
        });

        ButCadastroCadU1.setText("Cadastrar");
        ButCadastroCadU1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButCadastroCadU1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CadastroChaveLayout = new javax.swing.GroupLayout(CadastroChave);
        CadastroChave.setLayout(CadastroChaveLayout);
        CadastroChaveLayout.setHorizontalGroup(
            CadastroChaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadastroChaveLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CadastroChaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CadastroChaveLayout.createSequentialGroup()
                        .addComponent(LabTipoCadC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CBoxTipoCadC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CadastroChaveLayout.createSequentialGroup()
                        .addGroup(CadastroChaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabSalaCadC)
                            .addComponent(LabCapCadC))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 476, Short.MAX_VALUE)
                        .addGroup(CadastroChaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtSalaCadC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtCapacidadeCadC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CadastroChaveLayout.createSequentialGroup()
                .addGap(0, 579, Short.MAX_VALUE)
                .addComponent(ButCadastroCadU1))
        );
        CadastroChaveLayout.setVerticalGroup(
            CadastroChaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadastroChaveLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CadastroChaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabSalaCadC)
                    .addComponent(TxtSalaCadC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CadastroChaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabCapCadC)
                    .addComponent(TxtCapacidadeCadC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CadastroChaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabTipoCadC)
                    .addComponent(CBoxTipoCadC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 267, Short.MAX_VALUE)
                .addComponent(ButCadastroCadU1))
        );

        AbasChaves.addTab("Cadastrar", CadastroChave);

        ScrollPaneTab2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        TblUser1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Sala", "Capacidade", "Tipo", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TblUser1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TblUser1MouseClicked(evt);
            }
        });
        ScrollPaneTab2.setViewportView(TblUser1);

        ButAtualizarL1.setText("Atualizar");
        ButAtualizarL1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButAtualizarL1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ListaChaveLayout = new javax.swing.GroupLayout(ListaChave);
        ListaChave.setLayout(ListaChaveLayout);
        ListaChaveLayout.setHorizontalGroup(
            ListaChaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListaChaveLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ButAtualizarL1))
            .addGroup(ListaChaveLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ScrollPaneTab2, javax.swing.GroupLayout.DEFAULT_SIZE, 642, Short.MAX_VALUE)
                .addContainerGap())
        );
        ListaChaveLayout.setVerticalGroup(
            ListaChaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListaChaveLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ScrollPaneTab2, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButAtualizarL1))
        );

        AbasChaves.addTab("Listar", ListaChave);

        LabIdB1.setText("ID");

        LabLoginB1.setText("Sala");

        LabTipoB1.setText("Tipo");

        TxtIdBusC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtIdBusCActionPerformed(evt);
            }
        });

        TxtSalaBusC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtSalaBusCActionPerformed(evt);
            }
        });

        CBoxTipoBusC.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "S", "L", "R", "Nenhum" }));
        CBoxTipoBusC.setToolTipText("");
        CBoxTipoBusC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBoxTipoBusCActionPerformed(evt);
            }
        });

        ButBuscarBusU1.setText("Buscar");
        ButBuscarBusU1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButBuscarBusU1ActionPerformed(evt);
            }
        });

        LabLoginB2.setText("Capacidade");

        TxtCapacidadeBusC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCapacidadeBusCActionPerformed(evt);
            }
        });

        LabLoginB4.setText("Estado");

        ScrollPaneTab4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        TblChave.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Sala", "Capacidade", "Tipo", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TblChave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TblChaveMouseClicked(evt);
            }
        });
        ScrollPaneTab4.setViewportView(TblChave);

        CBoxEstadoBusC.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Disponivel", "Emprestada" }));
        CBoxEstadoBusC.setToolTipText("");
        CBoxEstadoBusC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBoxEstadoBusCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BuscaChaveLayout = new javax.swing.GroupLayout(BuscaChave);
        BuscaChave.setLayout(BuscaChaveLayout);
        BuscaChaveLayout.setHorizontalGroup(
            BuscaChaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BuscaChaveLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BuscaChaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ScrollPaneTab4)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BuscaChaveLayout.createSequentialGroup()
                        .addGroup(BuscaChaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabIdB1)
                            .addComponent(LabTipoB1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(BuscaChaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtIdBusC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CBoxTipoBusC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BuscaChaveLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ButBuscarBusU1))
                    .addGroup(BuscaChaveLayout.createSequentialGroup()
                        .addGroup(BuscaChaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabLoginB4)
                            .addComponent(LabLoginB1))
                        .addGap(367, 409, Short.MAX_VALUE)
                        .addGroup(BuscaChaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtSalaBusC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CBoxEstadoBusC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(BuscaChaveLayout.createSequentialGroup()
                        .addComponent(LabLoginB2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TxtCapacidadeBusC, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        BuscaChaveLayout.setVerticalGroup(
            BuscaChaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BuscaChaveLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BuscaChaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabIdB1)
                    .addComponent(TxtIdBusC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BuscaChaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabTipoB1)
                    .addComponent(CBoxTipoBusC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BuscaChaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabLoginB1)
                    .addComponent(TxtSalaBusC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BuscaChaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabLoginB2)
                    .addComponent(TxtCapacidadeBusC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BuscaChaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabLoginB4)
                    .addComponent(CBoxEstadoBusC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButBuscarBusU1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(ScrollPaneTab4, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        AbasChaves.addTab("Buscar", BuscaChave);

        LabIdA1.setText("ID");

        LabLoginA1.setText("Sala");

        LabSenhaNA1.setText("Capacidade");

        LabTipoA1.setText("Tipo");

        TxtIdAltC1.setEditable(false);

        TxtSenhaNAltC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtSenhaNAltC1ActionPerformed(evt);
            }
        });

        CBoxTipoAaltC1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "S", "L", "R" }));

        ButExcluirAltC1.setText("Excluir");
        ButExcluirAltC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButExcluirAltC1ActionPerformed(evt);
            }
        });

        ButAlterarAltC1.setText("Alterar");
        ButAlterarAltC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButAlterarAltC1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AlteraChaveLayout = new javax.swing.GroupLayout(AlteraChave);
        AlteraChave.setLayout(AlteraChaveLayout);
        AlteraChaveLayout.setHorizontalGroup(
            AlteraChaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AlteraChaveLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ButExcluirAltC1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButAlterarAltC1))
            .addGroup(AlteraChaveLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AlteraChaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AlteraChaveLayout.createSequentialGroup()
                        .addComponent(LabIdA1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TxtIdAltC1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AlteraChaveLayout.createSequentialGroup()
                        .addComponent(LabTipoA1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CBoxTipoAaltC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AlteraChaveLayout.createSequentialGroup()
                        .addComponent(LabSenhaNA1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TxtSenhaNAltC1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AlteraChaveLayout.createSequentialGroup()
                        .addComponent(LabLoginA1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 422, Short.MAX_VALUE)
                        .addComponent(TxtLoginAltC1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        AlteraChaveLayout.setVerticalGroup(
            AlteraChaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AlteraChaveLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AlteraChaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabIdA1)
                    .addComponent(TxtIdAltC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AlteraChaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabTipoA1)
                    .addComponent(CBoxTipoAaltC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AlteraChaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtLoginAltC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabLoginA1))
                .addGap(6, 6, 6)
                .addGroup(AlteraChaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtSenhaNAltC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabSenhaNA1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 241, Short.MAX_VALUE)
                .addGroup(AlteraChaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButAlterarAltC1)
                    .addComponent(ButExcluirAltC1)))
        );

        AbasChaves.addTab("Alterar", AlteraChave);

        Painel.add(AbasChaves, "card5");

        AbasUsuarios.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        AbasUsuarios.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        AbasUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        AbasUsuarios.setPreferredSize(new java.awt.Dimension(500, 600));

        LabLoginC.setText("Usuário");

        LabSenhaC.setText("Senha");

        LabSenhaRC.setText("Repita senha");

        LabTipoC.setText("Tipo");

        LabNomeC.setText("Nome");

        CBoxTipoCadU.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Administrador", "Funcionário" }));
        CBoxTipoCadU.setSelectedIndex(1);

        ButCadastroCadU.setText("Cadastrar");
        ButCadastroCadU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButCadastroCadUActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CadastroUsuarioLayout = new javax.swing.GroupLayout(CadastroUsuario);
        CadastroUsuario.setLayout(CadastroUsuarioLayout);
        CadastroUsuarioLayout.setHorizontalGroup(
            CadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadastroUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CadastroUsuarioLayout.createSequentialGroup()
                        .addComponent(LabTipoC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CBoxTipoCadU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CadastroUsuarioLayout.createSequentialGroup()
                        .addGroup(CadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabLoginC)
                            .addComponent(LabSenhaC)
                            .addComponent(LabNomeC)
                            .addComponent(LabSenhaRC))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(CadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TxtSenhaRCadU)
                            .addComponent(TxtUserCadU, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(TxtSenhaCadU, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TxtNomeCadU, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CadastroUsuarioLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ButCadastroCadU))
        );

        CadastroUsuarioLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {TxtNomeCadU, TxtSenhaCadU, TxtSenhaRCadU, TxtUserCadU});

        CadastroUsuarioLayout.setVerticalGroup(
            CadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadastroUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabNomeC)
                    .addComponent(TxtNomeCadU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabLoginC)
                    .addComponent(TxtUserCadU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabSenhaC)
                    .addComponent(TxtSenhaCadU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabSenhaRC)
                    .addComponent(TxtSenhaRCadU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabTipoC)
                    .addComponent(CBoxTipoCadU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 217, Short.MAX_VALUE)
                .addComponent(ButCadastroCadU))
        );

        AbasUsuarios.addTab("Cadastrar", CadastroUsuario);

        ScrollPaneTab.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        TblUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Login", "Tipo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TblUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TblUserMouseClicked(evt);
            }
        });
        ScrollPaneTab.setViewportView(TblUser);

        ButAtualizarL.setText("Atualizar");
        ButAtualizarL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButAtualizarLActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ListaUsuarioLayout = new javax.swing.GroupLayout(ListaUsuario);
        ListaUsuario.setLayout(ListaUsuarioLayout);
        ListaUsuarioLayout.setHorizontalGroup(
            ListaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListaUsuarioLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ButAtualizarL))
            .addGroup(ListaUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ScrollPaneTab, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
                .addContainerGap())
        );
        ListaUsuarioLayout.setVerticalGroup(
            ListaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListaUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ScrollPaneTab, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButAtualizarL))
        );

        AbasUsuarios.addTab("Listar", ListaUsuario);

        LabIdB.setText("ID");

        LabLoginB.setText("Login");

        LabTipoB.setText("Tipo");

        LabNomeB.setText("Nome");

        TxtIdBusU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtIdBusUActionPerformed(evt);
            }
        });

        TxtLoginBusU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtLoginBusUActionPerformed(evt);
            }
        });

        CBoxTipoBusU.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Administrador", "Funcionário", "Nenhum" }));
        CBoxTipoBusU.setSelectedIndex(2);
        CBoxTipoBusU.setToolTipText("");
        CBoxTipoBusU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBoxTipoBusUActionPerformed(evt);
            }
        });

        TxtNomeBusU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNomeBusUActionPerformed(evt);
            }
        });

        ScrollPaneTab1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        TblUserFiltro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Login", "Tipo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TblUserFiltro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TblUserFiltroMouseClicked(evt);
            }
        });
        ScrollPaneTab1.setViewportView(TblUserFiltro);

        ButBuscarBusU.setText("Buscar");
        ButBuscarBusU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButBuscarBusUActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BuscaUsuarioLayout = new javax.swing.GroupLayout(BuscaUsuario);
        BuscaUsuario.setLayout(BuscaUsuarioLayout);
        BuscaUsuarioLayout.setHorizontalGroup(
            BuscaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BuscaUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BuscaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BuscaUsuarioLayout.createSequentialGroup()
                        .addGroup(BuscaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabIdB)
                            .addComponent(LabLoginB)
                            .addComponent(LabTipoB)
                            .addComponent(LabNomeB))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 411, Short.MAX_VALUE)
                        .addGroup(BuscaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CBoxTipoBusU, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtNomeBusU, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(TxtLoginBusU)
                            .addComponent(TxtIdBusU, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(ScrollPaneTab1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BuscaUsuarioLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ButBuscarBusU)))
                .addContainerGap())
        );
        BuscaUsuarioLayout.setVerticalGroup(
            BuscaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BuscaUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BuscaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabIdB)
                    .addComponent(TxtIdBusU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BuscaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabTipoB)
                    .addComponent(CBoxTipoBusU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BuscaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabNomeB)
                    .addComponent(TxtNomeBusU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BuscaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabLoginB)
                    .addComponent(TxtLoginBusU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButBuscarBusU)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ScrollPaneTab1, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                .addContainerGap())
        );

        AbasUsuarios.addTab("Buscar", BuscaUsuario);

        LabIdA.setText("ID");

        LabLoginA.setText("Login");

        LabSenhaNA.setText("Nova senha");

        LabSenhaNRA.setText("Repita senha");

        LabTipoA.setText("Tipo");

        LabNomeA.setText("Nome");

        TxtIdAltC.setEditable(false);

        TxtSenhaNAltC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtSenhaNAltCActionPerformed(evt);
            }
        });

        CBoxTipoAaltC.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Administrador", "Funcionário" }));
        CBoxTipoAaltC.setSelectedIndex(1);

        ButExcluirAltC.setText("Excluir");
        ButExcluirAltC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButExcluirAltCActionPerformed(evt);
            }
        });

        ButAlterarAltC.setText("Alterar");
        ButAlterarAltC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButAlterarAltCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AlteraUsuarioLayout = new javax.swing.GroupLayout(AlteraUsuario);
        AlteraUsuario.setLayout(AlteraUsuarioLayout);
        AlteraUsuarioLayout.setHorizontalGroup(
            AlteraUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AlteraUsuarioLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ButExcluirAltC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButAlterarAltC))
            .addGroup(AlteraUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AlteraUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AlteraUsuarioLayout.createSequentialGroup()
                        .addComponent(LabIdA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TxtIdAltC, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AlteraUsuarioLayout.createSequentialGroup()
                        .addComponent(LabTipoA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CBoxTipoAaltC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AlteraUsuarioLayout.createSequentialGroup()
                        .addGroup(AlteraUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabLoginA)
                            .addComponent(LabNomeA)
                            .addComponent(LabSenhaNRA))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 375, Short.MAX_VALUE)
                        .addGroup(AlteraUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(TxtSenhaN2AltC, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtNomeAltC, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(TxtLoginAltC, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(AlteraUsuarioLayout.createSequentialGroup()
                        .addComponent(LabSenhaNA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TxtSenhaNAltC, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        AlteraUsuarioLayout.setVerticalGroup(
            AlteraUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AlteraUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AlteraUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabIdA)
                    .addComponent(TxtIdAltC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AlteraUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabTipoA)
                    .addComponent(CBoxTipoAaltC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AlteraUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabNomeA)
                    .addComponent(TxtNomeAltC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AlteraUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabLoginA)
                    .addComponent(TxtLoginAltC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AlteraUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabSenhaNA)
                    .addComponent(TxtSenhaNAltC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AlteraUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtSenhaN2AltC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabSenhaNRA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 191, Short.MAX_VALUE)
                .addGroup(AlteraUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButAlterarAltC)
                    .addComponent(ButExcluirAltC)))
        );

        AbasUsuarios.addTab("Alterar", AlteraUsuario);

        Painel.add(AbasUsuarios, "card2");

        LabDevolucaoCod.setText("Código");

        LabDevolucaoSala.setText("Sala");

        LabDevolucaoCap.setText("Capacidade");

        TxtDevolucaoCap.setEditable(false);

        LabDevolucaoID.setText("ID");

        TxtDevolucaoID.setEditable(false);

        ButtonDevolucaoBuscar.setText("Buscar");
        ButtonDevolucaoBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDevolucaoBuscarActionPerformed(evt);
            }
        });

        ButtonDevolucaoDevolver.setText("Realizar Devolução");
        ButtonDevolucaoDevolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDevolucaoDevolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AbaDevolucaoLayout = new javax.swing.GroupLayout(AbaDevolucao);
        AbaDevolucao.setLayout(AbaDevolucaoLayout);
        AbaDevolucaoLayout.setHorizontalGroup(
            AbaDevolucaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AbaDevolucaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AbaDevolucaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SeparatorDevolucao)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AbaDevolucaoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ButtonDevolucaoDevolver))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AbaDevolucaoLayout.createSequentialGroup()
                        .addComponent(LabDevolucaoCod)
                        .addGap(18, 18, 18)
                        .addComponent(TxtDevolucaoCod, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(LabDevolucaoSala)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TxtDevolucaoSala, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(LabDevolucaoCap)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TxtDevolucaoCap, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(LabDevolucaoID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TxtDevolucaoID, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 160, Short.MAX_VALUE)
                        .addComponent(ButtonDevolucaoBuscar)))
                .addContainerGap())
        );
        AbaDevolucaoLayout.setVerticalGroup(
            AbaDevolucaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AbaDevolucaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AbaDevolucaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonDevolucaoBuscar)
                    .addComponent(LabDevolucaoCod)
                    .addComponent(TxtDevolucaoCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabDevolucaoSala)
                    .addComponent(TxtDevolucaoSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabDevolucaoCap)
                    .addComponent(TxtDevolucaoCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabDevolucaoID)
                    .addComponent(TxtDevolucaoID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(SeparatorDevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ButtonDevolucaoDevolver)
                .addContainerGap(277, Short.MAX_VALUE))
        );

        Painel.add(AbaDevolucao, "card5");

        LabEmprestimoMatricula.setText("Matrícula");

        LabEmprestimoNome.setText("Nome");

        TxtEmprestimoNome.setEnabled(false);

        LabEmprestimoTipo.setText("Tipo");

        TxtEmprestimoTipo.setEnabled(false);

        ButtonEmprestimoPreencher.setText("Preencher");

        jLabel1.setText("Código");

        jLabel2.setText("Sala");

        jButton1.setText("Buscar");

        jButton2.setText("Realizar Empréstimo");

        jLabel3.setText("Capacidade");

        jTextField3.setEnabled(false);

        javax.swing.GroupLayout AbaEmprestimoLayout = new javax.swing.GroupLayout(AbaEmprestimo);
        AbaEmprestimo.setLayout(AbaEmprestimoLayout);
        AbaEmprestimoLayout.setHorizontalGroup(
            AbaEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AbaEmprestimoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AbaEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3)
                    .addComponent(jSeparator4)
                    .addGroup(AbaEmprestimoLayout.createSequentialGroup()
                        .addComponent(LabEmprestimoMatricula)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TxtEmprestimoMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(AbaEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(AbaEmprestimoLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(LabEmprestimoNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TxtEmprestimoNome)
                                .addGap(18, 18, 18)
                                .addComponent(LabEmprestimoTipo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TxtEmprestimoTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(AbaEmprestimoLayout.createSequentialGroup()
                                .addGap(400, 400, 400)
                                .addComponent(ButtonEmprestimoPreencher))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AbaEmprestimoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AbaEmprestimoLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        AbaEmprestimoLayout.setVerticalGroup(
            AbaEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AbaEmprestimoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AbaEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabEmprestimoMatricula)
                    .addComponent(TxtEmprestimoMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabEmprestimoNome)
                    .addComponent(TxtEmprestimoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabEmprestimoTipo)
                    .addComponent(TxtEmprestimoTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ButtonEmprestimoPreencher)
                .addGap(18, 18, 18)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(AbaEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(177, Short.MAX_VALUE))
        );

        Painel.add(AbaEmprestimo, "card4");

        ButSair.setText("Sair");
        ButSair.setToolTipText("");
        ButSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButSairActionPerformed(evt);
            }
        });

        ButLogout.setText("Logout");
        ButLogout.setToolTipText("");
        ButLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButLogoutActionPerformed(evt);
            }
        });

        ButLimpar.setText("Limpar");
        ButLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(Infos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ButLimpar)
                .addGap(6, 6, 6)
                .addComponent(ButLogout)
                .addGap(6, 6, 6)
                .addComponent(ButSair))
            .addComponent(Painel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Infos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Painel, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButLimpar)
                    .addComponent(ButLogout)
                    .addComponent(ButSair)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuUsuariosActionPerformed
        KeyControl.fachada.menuPainel(0, AbasUsuarios);
    }//GEN-LAST:event_MenuUsuariosActionPerformed

    private void ButCadastroCadUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButCadastroCadUActionPerformed
        KeyControl.fachada.cadastrarUsuario(
                TxtNomeCadU.getText(),
                TxtUserCadU.getText(),
                String.copyValueOf(TxtSenhaCadU.getPassword()),
                String.copyValueOf(TxtSenhaRCadU.getPassword()),
                CBoxTipoCadU.getSelectedIndex());
    }//GEN-LAST:event_ButCadastroCadUActionPerformed

    private void TblUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TblUserMouseClicked
        KeyControl.fachada.tabelaUsuarioSelecionada(TblUser.getSelectedRow());
    }//GEN-LAST:event_TblUserMouseClicked

    private void ButAtualizarLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButAtualizarLActionPerformed
        KeyControl.fachada.buscarUsuarios();
    }//GEN-LAST:event_ButAtualizarLActionPerformed

    private void ButSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ButSairActionPerformed

    private void ButLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButLogoutActionPerformed
        KeyControl.fachada.logout();
    }//GEN-LAST:event_ButLogoutActionPerformed

    private void ButLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButLimparActionPerformed
        KeyControl.fachada.limparTodosCampos(Painel);
    }//GEN-LAST:event_ButLimparActionPerformed

    private void TxtIdBusUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtIdBusUActionPerformed
        KeyControl.fachada.buscarUsuariosFiltrado();
    }//GEN-LAST:event_TxtIdBusUActionPerformed

    private void TxtLoginBusUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtLoginBusUActionPerformed
        KeyControl.fachada.buscarUsuariosFiltrado();
    }//GEN-LAST:event_TxtLoginBusUActionPerformed

    private void CBoxTipoBusUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBoxTipoBusUActionPerformed
        KeyControl.fachada.buscarUsuariosFiltrado();
    }//GEN-LAST:event_CBoxTipoBusUActionPerformed

    private void TxtNomeBusUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNomeBusUActionPerformed
        KeyControl.fachada.buscarUsuariosFiltrado();
    }//GEN-LAST:event_TxtNomeBusUActionPerformed

    private void TblUserFiltroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TblUserFiltroMouseClicked
        KeyControl.fachada.tabelaUsuarioSelecionada(TblUserFiltro.getSelectedRow());
    }//GEN-LAST:event_TblUserFiltroMouseClicked

    private void ButBuscarBusUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButBuscarBusUActionPerformed
        KeyControl.fachada.buscarUsuariosFiltrado();
    }//GEN-LAST:event_ButBuscarBusUActionPerformed

    private void ButExcluirAltCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButExcluirAltCActionPerformed
        KeyControl.fachada.excluirUsuario(Integer.parseInt(TxtIdAltC.getText()));
    }//GEN-LAST:event_ButExcluirAltCActionPerformed

    private void ButAlterarAltCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButAlterarAltCActionPerformed
        KeyControl.fachada.alterarUsuario(
                Integer.parseInt(TxtIdAltC.getText()),
                TxtNomeAltC.getText(),
                TxtLoginAltC.getText(),
                String.copyValueOf(TxtSenhaNAltC.getPassword()),
                CBoxTipoAaltC.getSelectedIndex(),
                String.copyValueOf(TxtSenhaN2AltC.getPassword()));
    }//GEN-LAST:event_ButAlterarAltCActionPerformed

    private void TxtSenhaNAltCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtSenhaNAltCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtSenhaNAltCActionPerformed

    private void MenuChavesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuChavesActionPerformed
        KeyControl.fachada.menuPainel(0, AbasChaves);
    }//GEN-LAST:event_MenuChavesActionPerformed

    private void ButCadastroCadU1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButCadastroCadU1ActionPerformed
        if (!"".equals(TxtCapacidadeCadC.getText())) {
            KeyControl.fachada.inserirChave(TxtSalaCadC.getText(),
                    Integer.parseInt(TxtCapacidadeCadC.getText()),
                    CBoxTipoCadC.getSelectedIndex());
        } else {
            KeyControl.fachada.inserirChave(TxtSalaCadC.getText(),
                    null,
                    CBoxTipoCadC.getSelectedIndex());
        }
    }//GEN-LAST:event_ButCadastroCadU1ActionPerformed

    private void TblUser1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TblUser1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TblUser1MouseClicked

    private void ButAtualizarL1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButAtualizarL1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButAtualizarL1ActionPerformed

    private void TxtIdBusCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtIdBusCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtIdBusCActionPerformed

    private void TxtSalaBusCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtSalaBusCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtSalaBusCActionPerformed

    private void CBoxTipoBusCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBoxTipoBusCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBoxTipoBusCActionPerformed

    private void ButBuscarBusU1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButBuscarBusU1ActionPerformed
        KeyControl.fachada.buscarChave(Integer.parseInt(!"".equals(TxtIdBusC.getText()) ? TxtIdBusC.getText() : null),
                TxtSalaBusC.getText(),
                Integer.parseInt(!"".equals(this.TxtCapacidadeBusC.getText()) ? this.TxtCapacidadeBusC.getText() : null),
                CBoxTipoBusC.getSelectedIndex(),
                CBoxEstadoBusC.getSelectedIndex());
    }//GEN-LAST:event_ButBuscarBusU1ActionPerformed

    private void TxtSenhaNAltC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtSenhaNAltC1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtSenhaNAltC1ActionPerformed

    private void ButExcluirAltC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButExcluirAltC1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButExcluirAltC1ActionPerformed

    private void ButAlterarAltC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButAlterarAltC1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButAlterarAltC1ActionPerformed

    private void MenuEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuEmprestimoActionPerformed
        KeyControl.fachada.menuPainel(1, AbaEmprestimo);
    }//GEN-LAST:event_MenuEmprestimoActionPerformed

    private void MenuDevolucaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuDevolucaoActionPerformed
        KeyControl.fachada.menuPainel(1, AbaDevolucao);
    }//GEN-LAST:event_MenuDevolucaoActionPerformed

    private void MenuReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuReservaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuReservaActionPerformed

    private void TxtCapacidadeBusCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCapacidadeBusCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCapacidadeBusCActionPerformed

    private void ButtonDevolucaoBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDevolucaoBuscarActionPerformed
        KeyControl.fachada.buscarChave(!"".equals(this.TxtDevolucaoSala.getText()) ? this.TxtDevolucaoSala.getText() : null);
    }//GEN-LAST:event_ButtonDevolucaoBuscarActionPerformed

    private void ButtonDevolucaoDevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDevolucaoDevolverActionPerformed
        KeyControl.fachada.devolverChave(!"".equals(TxtDevolucaoID.getText()) ? Integer.parseInt(TxtDevolucaoID.getText()) : null);
    }//GEN-LAST:event_ButtonDevolucaoDevolverActionPerformed

    private void CBoxTipoCadCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBoxTipoCadCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBoxTipoCadCActionPerformed

    private void TblChaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TblChaveMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TblChaveMouseClicked

    private void CBoxEstadoBusCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBoxEstadoBusCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBoxEstadoBusCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel AbaDevolucao;
    public javax.swing.JPanel AbaEmprestimo;
    public javax.swing.JTabbedPane AbasChaves;
    public javax.swing.JTabbedPane AbasUsuarios;
    public javax.swing.JPanel AlteraChave;
    public javax.swing.JPanel AlteraUsuario;
    public javax.swing.JPanel BuscaChave;
    public javax.swing.JPanel BuscaUsuario;
    public javax.swing.JButton ButAlterarAltC;
    public javax.swing.JButton ButAlterarAltC1;
    public javax.swing.JButton ButAtualizarL;
    public javax.swing.JButton ButAtualizarL1;
    public javax.swing.JButton ButBuscarBusU;
    public javax.swing.JButton ButBuscarBusU1;
    public javax.swing.JButton ButCadastroCadU;
    public javax.swing.JButton ButCadastroCadU1;
    public javax.swing.JButton ButExcluirAltC;
    public javax.swing.JButton ButExcluirAltC1;
    public javax.swing.JButton ButLimpar;
    public javax.swing.JButton ButLogout;
    public javax.swing.JButton ButSair;
    public javax.swing.JButton ButtonDevolucaoBuscar;
    public javax.swing.JButton ButtonDevolucaoDevolver;
    public javax.swing.JButton ButtonEmprestimoPreencher;
    public javax.swing.JComboBox CBoxEstadoBusC;
    public javax.swing.JComboBox CBoxTipoAaltC;
    public javax.swing.JComboBox CBoxTipoAaltC1;
    public javax.swing.JComboBox CBoxTipoBusC;
    public javax.swing.JComboBox CBoxTipoBusU;
    public javax.swing.JComboBox CBoxTipoCadC;
    public javax.swing.JComboBox CBoxTipoCadU;
    public javax.swing.JPanel CadastroChave;
    public javax.swing.JPanel CadastroUsuario;
    public javax.swing.JPanel Hora;
    public javax.swing.JPanel Infos;
    public javax.swing.JLabel LabCapCadC;
    public javax.swing.JLabel LabDevolucaoCap;
    public javax.swing.JLabel LabDevolucaoCod;
    public javax.swing.JLabel LabDevolucaoID;
    public javax.swing.JLabel LabDevolucaoSala;
    public javax.swing.JLabel LabEmprestimoMatricula;
    public javax.swing.JLabel LabEmprestimoNome;
    public javax.swing.JLabel LabEmprestimoTipo;
    public javax.swing.JLabel LabIdA;
    public javax.swing.JLabel LabIdA1;
    public javax.swing.JLabel LabIdB;
    public javax.swing.JLabel LabIdB1;
    public javax.swing.JLabel LabLoginA;
    public javax.swing.JLabel LabLoginA1;
    public javax.swing.JLabel LabLoginB;
    public javax.swing.JLabel LabLoginB1;
    public javax.swing.JLabel LabLoginB2;
    public javax.swing.JLabel LabLoginB4;
    public javax.swing.JLabel LabLoginC;
    public javax.swing.JLabel LabNomeA;
    public javax.swing.JLabel LabNomeB;
    public javax.swing.JLabel LabNomeC;
    public javax.swing.JLabel LabSalaCadC;
    public javax.swing.JLabel LabSenhaC;
    public javax.swing.JLabel LabSenhaNA;
    public javax.swing.JLabel LabSenhaNA1;
    public javax.swing.JLabel LabSenhaNRA;
    public javax.swing.JLabel LabSenhaRC;
    public javax.swing.JLabel LabTipoA;
    public javax.swing.JLabel LabTipoA1;
    public javax.swing.JLabel LabTipoB;
    public javax.swing.JLabel LabTipoB1;
    public javax.swing.JLabel LabTipoC;
    public javax.swing.JLabel LabTipoCadC;
    public javax.swing.JLabel LbHora;
    public javax.swing.JLabel LbNome;
    public javax.swing.JLabel LbTipo;
    public javax.swing.JPanel ListaChave;
    public javax.swing.JPanel ListaUsuario;
    public javax.swing.JPanel Menu;
    public javax.swing.JButton MenuChaves;
    public javax.swing.JButton MenuDevolucao;
    public javax.swing.JButton MenuEmprestimo;
    public javax.swing.JButton MenuReserva;
    public javax.swing.JButton MenuUsuarios;
    public javax.swing.JPanel Painel;
    public javax.swing.JScrollPane ScrollPaneTab;
    public javax.swing.JScrollPane ScrollPaneTab1;
    public javax.swing.JScrollPane ScrollPaneTab2;
    public javax.swing.JScrollPane ScrollPaneTab4;
    public javax.swing.JSeparator SeparatorDevolucao;
    public javax.swing.JTable TblChave;
    public javax.swing.JTable TblUser;
    public javax.swing.JTable TblUser1;
    public javax.swing.JTable TblUserFiltro;
    public javax.swing.JPanel Tipo;
    public javax.swing.JTextField TxtCapacidadeBusC;
    public javax.swing.JTextField TxtCapacidadeCadC;
    public javax.swing.JTextField TxtDevolucaoCap;
    public javax.swing.JTextField TxtDevolucaoCod;
    public javax.swing.JTextField TxtDevolucaoID;
    public javax.swing.JTextField TxtDevolucaoSala;
    public javax.swing.JTextField TxtEmprestimoMatricula;
    public javax.swing.JTextField TxtEmprestimoNome;
    public javax.swing.JTextField TxtEmprestimoTipo;
    public javax.swing.JTextField TxtIdAltC;
    public javax.swing.JTextField TxtIdAltC1;
    public javax.swing.JTextField TxtIdBusC;
    public javax.swing.JTextField TxtIdBusU;
    public javax.swing.JTextField TxtLoginAltC;
    public javax.swing.JTextField TxtLoginAltC1;
    public javax.swing.JTextField TxtLoginBusU;
    public javax.swing.JTextField TxtNomeAltC;
    public javax.swing.JTextField TxtNomeBusU;
    public javax.swing.JTextField TxtNomeCadU;
    public javax.swing.JTextField TxtSalaBusC;
    public javax.swing.JTextField TxtSalaCadC;
    public javax.swing.JPasswordField TxtSenhaCadU;
    public javax.swing.JPasswordField TxtSenhaN2AltC;
    public javax.swing.JPasswordField TxtSenhaNAltC;
    public javax.swing.JPasswordField TxtSenhaNAltC1;
    public javax.swing.JPasswordField TxtSenhaRCadU;
    public javax.swing.JTextField TxtUserCadU;
    public javax.swing.JPanel Usuario;
    public javax.swing.JButton jButton1;
    public javax.swing.JButton jButton2;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JSeparator jSeparator1;
    public javax.swing.JSeparator jSeparator3;
    public javax.swing.JSeparator jSeparator4;
    public javax.swing.JTextField jTextField1;
    public javax.swing.JTextField jTextField2;
    public javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
